version: '3'

tasks:
  npm:
    dir: ./gamefinder/frontend
    cmds:
      - npm {{.CLI_ARGS}}
  frontend:
    dir: ./gamefinder/frontend
    cmds:
      - npm run dev
  up:
    cmds:
      - docker compose up -d
      - task: frontend
  down:
    cmds:
      - docker compose down
  build:
    cmds:
      - docker build -t trainrex/gamefinder:latest .
  release:
    cmds:
      - task: build
      - docker tag trainrex/gamefinder:latest trainrex/gamefinder:{{.VERSION}}
      - docker push trainrex/gamefinder:latest
      - docker push trainrex/gamefinder:{{.VERSION}}
    vars:
      VERSION:
        sh: cat VERSION
